apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-job
  namespace: batch
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          serviceAccountName: spring-batch
          restartPolicy: onFailure
          containers:
            - name: demo-app-spring
              image: ${IMAGE}
              imagePullPolicy: IfNotPresent
              env:
                - name: SPRING_DATASOURCE_URL
                  value: jdbc:mysql://demo-app-mysql.batch.svc.cluster.local:3306/batch_process?useSSL=false&allowPublicKeyRetrieval=true
                - name: SPRING_DATASOURCE_USERNAME
                  valueFrom:
                    configMapKeyRef:
                      name: mysql-config-map
                      key: mysql-user-username
                - name: SPRING_DATASOURCE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-pass
                      key: mysql-user-password
                - name: PUSHGATEWAY_URL
                  value: "pg-prometheus-pushgateway.monitoring.svc:9091"
                - name: PUSHGATEWAY_JOBNAME
                  value: "spring-batch"
