apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-job
  namespace: batch
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 2
      ttlSecondsAfterFinished: 300
      template:
        spec:
          serviceAccountName: spring-batch
          restartPolicy: OnFailure
          containers:
            - name: demo-app-spring
              image: ${IMAGE}
              imagePullPolicy: IfNotPresent
              env:
                - name: SPRING_DATASOURCE_URL
                  value: jdbc:mysql://demo-app-mysql.batch.svc.cluster.local:3306/batch_process?useSSL=false&allowPublicKeyRetrieval=true
                - name: SPRING_DATASOURCE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: batch-mysql-auth-k8s
                      key: username
                - name: SPRING_DATASOURCE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: batch-mysql-auth-k8s
                      key: mysql-user-password
                - name: PUSHGATEWAY_URL
                  value: "pg-prometheus-pushgateway.monitoring.svc:9091"
                - name: PUSHGATEWAY_JOBNAME
                  value: "spring-batch"
              volumeMounts:
              - name: secrets-store
                mountPath: "/mnt/secrets"
                readOnly: true
          volumes:
            - name: secrets-store
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: aws-secrets