#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: demo-app-spring
#  labels:
#    app: demo-app-spring
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: demo-app-spring
#  template:
#    metadata:
#      labels:
#        app: demo-app-spring
#    spec:
#      containers:
#        - name: demo-app-spring
#          image: 557690581666.dkr.ecr.eu-west-1.amazonaws.com/spring-batch-eks:latest
#          imagePullPolicy: IfNotPresent
#          ports:
#            - name: http
#              containerPort: 8080
#          resources:
#            limits:
#              cpu: 0.2
#              memory: "200Mi"
#          env:
#            - name: DB_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: mysql-pass
#                  key: mysql-user-password
#            - name: DB_SERVER
#              valueFrom:
#                configMapKeyRef:
#                  name:  mysql-config-map
#                  key: mysql-server
#            - name: DB_NAME
#              valueFrom:
#                configMapKeyRef:
#                  name:  mysql-config-map
#                  key: mysql-database-name
#            - name: DB_USERNAME
#              valueFrom:
#                configMapKeyRef:
#                  name: mysql-config-map
#                  key: mysql-user-username
#
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: demo-app-spring
#  labels:
#    app: demo-app-spring
#spec:
#  type: LoadBalancer
#  selector:
#    app: demo-app-spring
#  ports:
#    - protocol: TCP
#      name: http
#      port: 8080
#      targetPort: 8080
#      nodePort: 30000


#apiVersion: batch/v1
#kind: Job
#metadata:
#  name: batch-job
#spec:
#  template:
#    spec:
#      restartPolicy: OnFailure
##      initContainers:
##        - name: init-db
##          image: mysql:5.6
##          command: [ 'sh', '-c', 'mysql -h $DB_SERVER -u$DB_USERNAME -p$DB_PASSWORD $DB_NAME < /scripts/schema.sql' ]
###          command: ["sh", "-c", "echo DB_SERVER=$DB_SERVER DB_USERNAME=$DB_USERNAME DB_PASSWORD=$DB_PASSWORD DB_NAME=$DB_NAME && sleep 300"]
##          env:
##            - name: DB_SERVER
##              valueFrom:
##                configMapKeyRef:
##                  name: mysql-config-map
##                  key: mysql-server
##            - name: DB_USERNAME
##              valueFrom:
##                configMapKeyRef:
##                  name: mysql-config-map
##                  key: mysql-user-username
##            - name: DB_PASSWORD
##              valueFrom:
##                secretKeyRef:
##                  name: mysql-pass
##                  key: mysql-user-password
##            - name: DB_NAME
##              valueFrom:
##                configMapKeyRef:
##                  name: mysql-config-map
##                  key: mysql-database-name
##          volumeMounts:
##            - name: init-sql-volume
##              mountPath: /scripts
##              readOnly: true
#      containers:
#        - name: demo-app-spring
#          image:  ${IMAGE}
##          image: 557690581666.dkr.ecr.eu-west-1.amazonaws.com/spring-batch-eks:latest
#          imagePullPolicy: IfNotPresent
#          env:
#            - name: SPRING_DATASOURCE_URL
##              value: jdbc:mysql://$(DB_SERVER):3306/$(DB_NAME)?useSSL=false&allowPublicKeyRetrieval=true
#              value: jdbc:mysql://demo-app-mysql.default.svc.cluster.local:3306/batch_process?useSSL=false&allowPublicKeyRetrieval=true
##            - name: DB_PASSWORD
##              valueFrom:
##                secretKeyRef:
##                  name: mysql-pass
##                  key: mysql-user-password
#            - name: SPRING_DATASOURCE_USERNAME
#              valueFrom:
#                configMapKeyRef:
#                  name: mysql-config-map
#                  key: mysql-user-username
#            - name: SPRING_DATASOURCE_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: mysql-pass
#                  key: mysql-user-password
##            - name: DB_SERVER
##              valueFrom:
##                configMapKeyRef:
##                  name:  mysql-config-map
##                  key: mysql-server
##            - name: DB_NAME
##              valueFrom:
##                configMapKeyRef:
##                  name:  mysql-config-map
##                  key: mysql-database-name
##            - name: DB_USERNAME
##              valueFrom:
##                configMapKeyRef:
##                  name: mysql-config-map
##                  key: mysql-user-username
##      volumes:
##        - name: init-sql-volume
##          configMap:
##            name: init-sql-script


apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-job
  namespace: batch
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: spring-batch
          restartPolicy: Never
          containers:
            - name: demo-app-spring
              image: ${IMAGE}
              imagePullPolicy: IfNotPresent
              env:
                - name: SPRING_DATASOURCE_URL
                  value: jdbc:mysql://demo-app-mysql.default.svc.cluster.local:3306/batch_process?useSSL=false&allowPublicKeyRetrieval=true
                - name: SPRING_DATASOURCE_USERNAME
                  valueFrom:
                    configMapKeyRef:
                      name: mysql-config-map
                      key: mysql-user-username
                - name: SPRING_DATASOURCE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-pass
                      key: mysql-user-password
                - name: PUSHGATEWAY_URL
                  value: "http://pg-prometheus-pushgateway.monitoring.svc:9091"
                - name: METRICS_JOB_NAME
                  value: "spring-batch"
              command: ["/bin/sh","-c"]
              args:
                - |
                  set -eu

                  echo ">> Ensuring curl exists..."
                  have_curl() { command -v curl >/dev/null 2>&1; }
                  if ! have_curl; then (command -v apk >/dev/null 2>&1 && apk add --no-cache curl) || true; fi
                  if ! have_curl; then (command -v apt-get >/dev/null 2>&1 && apt-get update && apt-get install -y curl) || true; fi
                  if ! have_curl; then (command -v yum >/dev/null 2>&1 && yum install -y curl) || true; fi
                  if ! have_curl; then echo "!! curl still not available; metrics will NOT be pushed"; fi

                  echo ">> Starting Spring Batch job at $(date)"
                  start=$(date +%s)

                  # --- Run your Spring Batch app ONCE with a unique run.id ---
                  status=0
                  if [ -x "/entrypoint.sh" ]; then
                    /entrypoint.sh run.id=$(date +%s) || status=$?
                  elif command -v java >/dev/null 2>&1 && ls /app/*.jar >/dev/null 2>&1; then
                    java -jar /app/*.jar run.id=$(date +%s) || status=$?
                  elif command -v java >/dev/null 2>&1 && ls *.jar >/dev/null 2>&1; then
                    java -jar *.jar run.id=$(date +%s) || status=$?
                  else
                    echo "!! Could not find how to start the app. Skipping run."
                    status=1
                  fi

                  end=$(date +%s)
                  duration=$((end - start))
                  echo ">> Job exit code: ${status}, duration: ${duration}s"

                  # Build metrics file
                  cat <<EOF >/tmp/metrics.prom
                  # TYPE batch_runs_total counter
                  batch_runs_total{app="spring-batch",exit_code="${status}"} 1
                  # TYPE batch_duration_seconds gauge
                  batch_duration_seconds{app="spring-batch",exit_code="${status}"} ${duration}
                  EOF

                  # Push to Pushgateway (URL path sets job label = spring-batch)
                  if have_curl; then
                    echo ">> Pushing metrics to ${PUSHGATEWAY_URL}"
                    http_code=$(curl -s -o /tmp/pg.out -w "%{http_code}" --data-binary @/tmp/metrics.prom \
                      ${PUSHGATEWAY_URL}/metrics/job/spring-batch/instance/$HOSTNAME || true)
                    echo ">> Pushgateway HTTP status: ${http_code}"
                    [ "${http_code}" = "202" ] && echo ">> Push OK" || (echo "!! Push failed"; cat /tmp/pg.out || true)
                  fi

                  # Exit with the app's status so K8s records success/failure correctly
                  exit ${status}
