apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-cosign-signatures
spec:
  validationFailureAction: enforce
  background: false
  rules:
    - name: verify-signed-images
      match:
        resources:
          kinds:
            - Pod
      verifyImages:
        - image: "557690581666.dkr.ecr.eu-west-1.amazonaws.com/*:latest"
          key: "cosign.pub"
          keyRef:
            name: cosign-pub-key
            namespace: kyverno
          repository: "557690581666.dkr.ecr.eu-west-1.amazonaws.com"