apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-cosign-signatures
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: verify-signed-images
      match:
        any:
          - resources:
              kinds:
                - Pod
                - Job
                - CronJob
      context:
        - name: cosignKey
          configMap:
            name: cosign-pub-key
            namespace: kyverno
      verifyImages:
        - imageReferences:
          - "557690581666.dkr.ecr.eu-west-1.amazonaws.com/*:*"
          - "557690581666.dkr.ecr.eu-west-1.amazonaws.com/*@sha256:*"
          key: "{{ cosignKey.data.cosign_pub }}"
          repository: "557690581666.dkr.ecr.eu-west-1.amazonaws.com"