apiVersion: v1
kind: Namespace
metadata:
  name: batch
---
apiVersion: v1
kind: Namespace
metadata:
  name: cicd

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-batch
  namespace: batch
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::557690581666:role/SpringBatchIRSA
---
# spring-batch Role & Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spring-batch-role
  namespace: batch
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "jobs", "secrets"]
    verbs: ["get", "list", "create", "delete", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring-batch-rolebinding
  namespace: batch
subjects:
  - kind: ServiceAccount
    name: spring-batch
    namespace: batch
roleRef:
  kind: Role
  name: spring-batch-role
  apiGroup: rbac.authorization.k8s.io
---
# Service Account for CICD Deployer
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-deployer
  namespace: cicd
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::557690581666:role/CICDDeployerIRSA
---
# cicd-deployer Role & Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cicd-deployer-role
  namespace: cicd
rules:
  - apiGroups: ["", "apps", "batch"]
    resources: ["deployments", "services", "configmaps", "jobs"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd-deployer-rolebinding
  namespace: cicd
subjects:
  - kind: ServiceAccount
    name: cicd-deployer
    namespace: cicd
roleRef:
  kind: Role
  name: cicd-deployer-role
  apiGroup: rbac.authorization.k8s.io

