#apiVersion: v1
#kind: Secret
#metadata:
#  name: mysql-pass
#  namespace: batch
#type: Opaque
#data:
#  mysql-root-password: cGFzc3dvcmQ=  #rootpassword
#  mysql-user-password: cGFzc3dvcmQ=  #userpassword
#
#---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mysql-pass
  namespace: batch
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "batch-mysql-auth"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "username"
          - path: "mysql-user-password"
            objectAlias: "mysql-user-password"
          - path: "mysql-root-password"
            objectAlias: "mysql-root-password"
          - path: "host"
            objectAlias: "host"
          - path: "port"
            objectAlias: "port"
  secretObjects:
    - secretName: batch-mysql-auth-k8s
      type: Opaque
      data:
        - objectName: "username"
          key: username
        - objectName: "mysql-root-password"
          key: mysql-root-password
        - objectName: "mysql-user-password"
          key: mysql-user-password
        - objectName: "host"
          key: host
        - objectName: "port"
          key: port