name: app-deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      IMAGE_TAG: ${{ github.sha }}
      EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        working-directory: ./initial
        run: mvn --batch-mode clean test package

    #   - name: Configure AWS credentials
    #     uses: aws-actions/configure-aws-credentials@v2
    #     with:
    #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       aws-region: ${{ env.AWS_REGION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::557690581666:role/GitHubActionsEKSRole
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        working-directory: ./initial
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.30.0
        with:
            image-ref: '${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}'
            format: 'sarif'
            output: 'trivy-results.sarif'
            exit-code: 0 # Set to 1 if you want to fail on vulnerabilities
            severity: 'CRITICAL,HIGH'

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.3.0
        with:
          cosign-release: 'v2.2.2'

      - name: Sign Docker image
        env:
          COSIGN_EXPERIMENTAL: "1"
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
        run: |
          IMAGE="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
          echo "$COSIGN_KEY" > cosign.key
          cosign sign --key cosign.key $IMAGE

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

      - name: Apply MySQL Config & Deployment
        working-directory: ./initial
        run: |
          kubectl create namespace batch --dry-run=client -o yaml | kubectl apply -f -
          kubectl create configmap init-sql-script --from-file=src/main/resources/schema.sql -n batch --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -n batch -f mysql-configmap.yaml
          kubectl apply -n batch -f secrets.yaml
          kubectl apply -n batch -f mysql-deployment.yaml

      - name: Wait for MySQL to be ready
        run: kubectl wait --for=condition=ready pod -l app=demo-app --timeout=120s -n batch

      - name: Deploy CronJob
        working-directory: ./initial
        run: |
          export IMAGE="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
          envsubst < app-deployment.yaml > final-cronjob.yaml
          kubectl apply -f final-cronjob.yaml
